"""
GAOS™ MODULE 36 — Monthly Cost Rollup Reporter
Zone 7: Utility | Standalone: £350 | In: Virtual Finance, Full Team

On the 1st of every month reads the Usage_Log sheet and emails a clean
cost breakdown to the admin address.  Covers:
  • DeepSeek API tokens & cost per module
  • Groq tokens (free tier — tracked for volume visibility)
  • Gross margin estimate vs subscription revenue

Sheet tab required: Usage_Log
Columns: Timestamp | Module | Tokens | Cost GBP
(Populated automatically by the AI manager on every successful call;
the Module column holds the provider name — deepseek / groq.)

Target client:  Any GAOS subscriber who wants to see the AI running cost.
Pain solved:    Unknown AI cost creep; justifying the subscription value.
"""

from datetime import datetime
import gaos_core as core

log = core.get_logger("cost_rollup")

SEND_HOUR = 9


def _tick(gmail, cfg):
    if core.should_run_at(SEND_HOUR, day_of_month=1):
        generate_monthly_report(gmail, cfg)


def run():
    cfg   = core.load_config()
    gmail = core.connect_gmail()
    log.info("Scheduled: 1st of every month at %d:00. Ctrl+C to stop.", SEND_HOUR)
    core.run_loop(lambda: _tick(gmail, cfg),
                  cfg.get("settings", {}).get("check_every_seconds", 300))


def generate_monthly_report(gmail, cfg):
    log.info("Generating monthly cost rollup...")

    sheet_id = cfg["google_sheets"]["sheet_id"]
    tabs     = cfg["google_sheets"]["tabs"]

    usage_rows = core.sheets_read_all(sheet_id, tabs.get("usage_log", "Usage_Log"))
    if not usage_rows:
        log.info("No usage data found — skipping report.")
        return

    now         = datetime.now()
    last_month  = now.month - 1 if now.month > 1 else 12
    last_year   = now.year  if now.month > 1 else now.year - 1
    period_str  = f"{last_year}-{last_month:02d}"

    rows = [r for r in usage_rows
            if str(r.get("Timestamp", "")).startswith(period_str)]
    if not rows:
        log.info("No usage data for %s — skipping report.", period_str)
        return

    module_stats: dict = {}
    total_tokens = 0
    total_cost   = 0.0

    for r in rows:
        mod    = str(r.get("Module", "unknown"))
        tokens = core.safe_int(r.get("Tokens", 0), 0)
        try:
            cost = float(str(r.get("Cost GBP", 0) or 0).replace("£", ""))
        except ValueError:
            cost = 0.0
        if mod not in module_stats:
            module_stats[mod] = {"calls": 0, "tokens": 0, "cost": 0.0}
        module_stats[mod]["calls"]  += 1
        module_stats[mod]["tokens"] += tokens
        module_stats[mod]["cost"]   += cost
        total_tokens += tokens
        total_cost   += cost

    # Revenue estimate
    role_prices  = {"admin": 199, "sales": 199, "finance": 249,
                    "receptionist": 299, "marketer": 199, "intelligence": 149}
    active_roles = cfg.get("active_roles", [])
    if active_roles:
        monthly_rev = sum(role_prices.get(r, 0) for r in active_roles)
    else:
        monthly_rev = 999   # full team default

    margin     = monthly_rev - total_cost
    margin_pct = (margin / monthly_rev * 100) if monthly_rev else 0

    # AI provider summary
    try:
        import gaos_ai
        ai_status = gaos_ai.get_ai_status()
        ai_lines  = [f"  {p['name'].title():12s} {p['calls']:5d} calls  "
                     f"{p['tokens']:9,d} tokens  £{p['cost_gbp']:.4f}"
                     for p in ai_status.get("providers", [])]
    except ImportError:
        ai_lines = ["  (gaos_ai not available — per-provider breakdown unavailable)"]

    lines = [
        f"GAOS™ Monthly Cost Report — {cfg['business']['name']}",
        f"Period: {period_str}",
        "=" * 56,
        "",
        f"Total API Calls:   {len(rows):,}",
        f"Total Tokens:      {total_tokens:,}",
        f"Total AI Cost:     £{total_cost:.4f}",
        "",
        "By Provider:",
        "-" * 56,
        *ai_lines,
        "",
        "By Provider from Usage_Log (top 10 by cost):",
        "-" * 56,
    ]
    for mod, stats in sorted(module_stats.items(),
                             key=lambda x: -x[1]["cost"])[:10]:
        lines.append(f"  {mod:30s} {stats['calls']:4d} calls  "
                     f"{stats['tokens']:8,d} tokens  £{stats['cost']:.4f}")
    lines += [
        "",
        "=" * 56,
        f"Subscription Revenue (est.):  £{monthly_rev:,}",
        f"AI Cost:                      £{total_cost:.4f}",
        f"Gross Margin:                 £{margin:,.2f}  ({margin_pct:.1f}%)",
        "",
        "Generated by GAOS™ Module 36 — Cost Rollup Reporter",
        "Aether Frameworks",
    ]

    alert_email = cfg["gmail"]["alert_email"]
    core.gmail_send(
        gmail,
        alert_email,
        cfg["gmail"]["watch_inbox"],
        f"[GAOS] Monthly Cost Report — {cfg['business']['name']} — {period_str}",
        "\n".join(lines),
    )
    core.log_action(cfg, "cost_rollup", "monthly_report", "ok",
                    f"period={period_str} cost=£{total_cost:.4f} margin={margin_pct:.1f}%")
    log.info("Cost report sent to %s. AI cost: £%.4f, margin: %.1f%%",
             alert_email, total_cost, margin_pct)


if __name__ == "__main__":
    run()
